// const fcc = React.createElement('i', { key: 'c11'}, 'Italic React');
// const fc = React.createElement('span', { key: 'c1'}, [fcc]);
// const sc = React.createElement('b', { key: 'c2'}, 'Bold React');
// console.log(sc);
// const h2 = React.createElement('h2', { id:'firstElement' }, [sc, fc]);
// console.log(h2);
const h2 = /*#__PURE__*/React.createElement("h2", null, "React Element");
console.log(h2);
const root = ReactDOM.createRoot(document.querySelector('#root'));
root.render(h2);